// components/pagination-dots/index.vue
<template>
  <div className="mt-10 flex flex-row gap-2">
    <template v-for="(item, i) in sliderItems" :key="i">
      <button
        type="button"
        :class="`rounded-full w-4 h-4 ${
          i === currentIndex ? 'bg-mint' : 'bg-dark'
        }`"
        @click="$emit('pagination', i)"
        aria-label="click"
      />
    </template>
  </div>
</template>

<script lang="ts" setup>
defineProps({
  sliderItems: { type: Array, required: true },
  currentIndex: { type: Number, required: true },
});
</script>

<style lang="postcss" scoped></style>

// components/slider/PaginationDots.jsx
import React from 'react'

const PaginationDots = ({ sliderItems, currentIndex, handleClick }) => {
  return (
    <div className="mt-10 flex flex-row gap-2">
      {sliderItems.map((_, i) => {
        return (
          <button
            type="button"
            key={i}
            className={`rounded-full w-4 h-4 ${
              i === currentIndex ? 'bg-mint' : 'bg-dark'
            }`}
            onClick={() => {
              handleClick(i)
            }}
          />
        )
      })}
    </div>
  )
}

export default PaginationDots
