// components/project-card/index.vue
<template>
  <div
    v-if="active"
    class="bg-white/70 flex flex-col items-center justify-center min-h-fit shadow-lg p-2 py-8"
  >
    <div class="underline-gradient font-serif text-4xl text-center">
      {{ title }}
    </div>
    <div class="my-4">{{ emoji }}</div>
    <div class="content-big text-center font-light mb-4 mx-10">
      {{ description }}
    </div>
    <div class="flex flex-col md:flex-row gap-4 flex-wrap md:flex-nowrap">
      <a
        v-if="link"
        class="button-gradient-small"
        :href="link"
        aria-label="click"
      >
        {{ projectCard.link }}
      </a>
      <a
        v-if="codeLink"
        :href="codeLink"
        class="button-gradient-small"
        aria-label="click"
      >
        {{ projectCard.codeLink }}
      </a>
    </div>
  </div>
</template>

<script lang="ts" setup>
import projectCard from '~/content/project-card.json';

defineProps({
  active: { type: Boolean, required: true },
  title: { type: String, default: 'No title.' },
  emoji: { type: String, default: undefined },
  description: { type: String, default: 'No description.' },
  link: { type: String, default: undefined },
  codeLink: { type: String, default: undefined },
});
</script>

// components/projects/ProjectCard.jsx
import Image from 'next/image'
import React from 'react'
import GithubIcon from '../../public/assets/github.svg'

const ProjectCard = ({ active, title, emoji, description, link, codeLink }) => {
  return (
    <>
      {active && (
        <div className="flex flex-col items-center justify-center min-h-fit">
          <div className="underline-gradient font-serif text-4xl">{title}</div>
          <div className="my-4">{emoji}</div>
          <div className="content-big text-center font-light mb-4 mx-10">
            {description}
          </div>
          <div className="flex flex-row gap-4 flex-wrap md:flex-nowrap">
            {link && (
              <a
                className="button-gradient-small"
                href={link}
                aria-label="click"
              >
                Go to Project
              </a>
            )}
            {codeLink && (
              <a
                href={codeLink}
                className="button-gradient-small"
                aria-label="click"
              >
                Go to Code
              </a>
            )}
          </div>
        </div>
      )}
    </>
  )
}

export default ProjectCard
